# Generated by Django 4.2.2 on 2023-06-23 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_question_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='time',
        ),
        migrations.AddField(
            model_name='speech',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
