# Generated by Django 4.2.2 on 2023-06-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_speech_time_speech_end_time_speech_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_id',
            new_name='username',
        ),
    ]
