# Generated by Django 4.2.2 on 2023-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_telegram_id_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
